version: '3.8'

services:
  llm-survey:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
        SCIMCP_DATA_PATH: ${SCIMCP_DATA_PATH:-/app/data/all_papers.parquet}
    image: llm-surveying-llms:latest
    container_name: llm-survey-container
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SCIMCP_DATA_PATH=${SCIMCP_DATA_PATH:-/app/data/all_papers.parquet}
      - CACHE_DIR=/app/cache
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_RATE_LIMIT_DELAY=${API_RATE_LIMIT_DELAY:-3}
    volumes:
      # Data volume for papers dataset
      - ${HOST_DATA_PATH:-./data}:/app/data
      # Output volume for results
      - ${HOST_OUTPUT_PATH:-./outputs}:/app/outputs
      # Cache volume for performance
      - llm-survey-cache:/app/cache
      # Optional: Mount source code for development
      # - ./src:/app/src:ro
    ports:
      # Optional: Expose port if adding web interface
      - "8080:8080"
    networks:
      - llm-survey-network
    restart: unless-stopped
    mem_limit: 4g
    cpus: '2.0'
    command: python simplified_demo.py

  # Optional: Jupyter notebook service for interactive development
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm-surveying-llms:latest
    container_name: llm-survey-jupyter
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SCIMCP_DATA_PATH=${SCIMCP_DATA_PATH:-/app/data/all_papers.parquet}
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${HOST_DATA_PATH:-./data}:/app/data
      - ${HOST_OUTPUT_PATH:-./outputs}:/app/outputs
      - llm-survey-cache:/app/cache
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    networks:
      - llm-survey-network
    command: >
      sh -c "pip install jupyterlab &&
             jupyter lab --ip=0.0.0.0 --port=8888 --no-browser 
             --allow-root --NotebookApp.token='' --NotebookApp.password=''"
    profiles:
      - dev

volumes:
  llm-survey-cache:
    driver: local

networks:
  llm-survey-network:
    driver: bridge